version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: exampleuser
            POSTGRES_PASSWORD: examplepass
            POSTGRES_DB: exampledb
            POSTGRES_INITDB_ARGS: '--data-checksums'
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U exampleuser']
            interval: 30s
            timeout: 10s
            retries: 5
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

volumes:
    postgres_data:
