services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 30s
            timeout: 10s
            retries: 5
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

volumes:
    postgres_data:
